### ISSUE TITLE
How to organize and distribute data

### ISSUE THREAD

**Issue by peastman** [openmm/spice-dataset#21]
Because of limitations in qcfractal, we had to break up the dataset into many pieces and generate them separately.  It's still intended to be a single dataset, though.  How can we make it easy for someone to obtain the entire dataset all at once?

A related issue is that we'll continue generating data and producing regular versioned releases.  A paper might say, "The model was trained on SPICE version 2."  A person who wants to reproduce the work needs an easy way to download that version and be sure they're getting exactly the data used in the paper.

How can we do this?

**Comment by jchodera** [comment]
@pavankum @dotsdl @jthorton may know more about how we can do this.

**Comment by pavankum** [comment]
>A paper might say, "The model was trained on SPICE version 2."

Yeah, we agree with this, we discussed the same in last QCF meeting and the consensus is to download the data and upload to zenodo with "date-accessed", that would decouple it from any changes to the living database, the updates to the software to access those datasets, and adding more completed calculations. Any other suggestions are welcome.

>  It's still intended to be a single dataset, though. 

Once we figure out the hdf5 output it should be easy to patch together data from multiple datasets if that's intended. 
 @dotsdl / @jthorton may add more.

**Comment by peastman** [comment]
There's been some relevant discussion over at #11, particularly @jthorton's [suggestion](https://github.com/openmm/spice-dataset/issues/11#issuecomment-1104879379) that we handle this with an API in qcsubmit.  I'm replying here since it's more on topic for this issue.

The main thing is to make sure it's easy for users.  Anything that requires them to write code just to download the dataset creates a huge barrier.  If it requires them to learn the API for qcsubmit or qcportal, that's an even bigger barrier.

One option is to provide the data in multiple forms.  We can provide a downloader application that internally uses qcsubmit and/or qcportal, but doesn't require the user to write any code.  They just edit a configuration file to specify what data they want and run it.  Then we can use that program to generate a file containing only the most important information.  Most users can just download that file, which should be only a few GB.  People who want less common data fields can run the downloader.

**Comment by giadefa** [comment]
what about a version variable in the hdf5 file?

**Comment by peastman** [comment]
Here's an updated version of the downloader that uses a configuration file to specify what to include.

```python
from qcportal import FractalClient
from collections import defaultdict
import numpy as np
import h5py
import yaml

with open('config.yaml') as input:
    config = yaml.safe_load(input.read())
client = FractalClient()
outputfile = h5py.File('SPICE.hdf5', 'w')
for subset in config['subsets']:
    print('Processing', subset)
    ds = client.get_collection('Dataset', subset)
    all_molecules = ds.get_molecules()
    spec = ds.list_records().iloc[0].to_dict()
    recs = ds.get_records(method=spec['method'], basis=spec['basis'], program=spec['program'], keywords=spec['keywords'])
    recs_by_name = defaultdict(list)
    mols_by_name = defaultdict(list)
    for i in range(len(recs)):
        rec = recs.iloc[i]
        index = recs.index[i]
        name = index[:index.rfind('-')]
        recs_by_name[name].append(rec.record)
        mols_by_name[name].append(all_molecules.loc[index][0])
    for name in recs_by_name:
        group = outputfile.create_group(name)
        group_recs = recs_by_name[name]
        molecules = mols_by_name[name]
        qcvars = [r.extras['qcvars'] for r in group_recs]
        group.create_dataset('subset', data=[subset], dtype=h5py.string_dtype())
        group.create_dataset('smiles', data=[molecules[0].extras['canonical_isomeric_explicit_hydrogen_mapped_smiles']], dtype=h5py.string_dtype())
        group.create_dataset("atomic_numbers", data=molecules[0].atomic_numbers, dtype=np.int16)
        conformations = group.create_dataset('conformations', data=np.array([m.geometry for m in molecules]), dtype=np.float32)
        for value in config['values']:
            key = value.lower().replace(' ', '_')
            group.create_dataset(key, data=np.array([vars[value] for vars in qcvars]), dtype=np.float32)
```

Here is the configuration file for it.

```yaml
subsets:
  - 'SPICE Solvated Amino Acids Single Points Dataset v1.1'
  - 'SPICE Dipeptides Single Points Dataset v1.2'
  - 'SPICE DES Monomers Single Points Dataset v1.1'
  - 'SPICE DES370K Single Points Dataset v1.0'
  - 'SPICE DES370K Single Points Dataset Supplement v1.0'
  - 'SPICE PubChem Set 1 Single Points Dataset v1.2'
  - 'SPICE PubChem Set 2 Single Points Dataset v1.2'
  - 'SPICE PubChem Set 3 Single Points Dataset v1.2'
  - 'SPICE PubChem Set 4 Single Points Dataset v1.0'
  - 'SPICE PubChem Set 5 Single Points Dataset v1.0'
  - 'SPICE PubChem Set 6 Single Points Dataset v1.0'
values:
  - 'DFT TOTAL ENERGY'
  - 'DFT TOTAL GRADIENT'
  - 'MBIS CHARGES'
  - 'MBIS DIPOLES'
  - 'MBIS QUADRUPOLES'
  - 'MBIS OCTUPOLES'
  - 'SCF DIPOLE'
  - 'SCF QUADRUPOLE'
  - 'WIBERG LOWDIN INDICES'
  - 'MAYER INDICES'
```

It's a lot faster than the previous version.  I estimate that downloading the entire dataset will take less than a day.  Most of the time is now spent in `ds.get_records()`.  Is there any way to speed that up?

If we remove all the values except `'DFT TOTAL ENERGY'` and `'DFT TOTAL GRADIENT'`, the complete dataset should only be 1-2 GB.  We can easily create that version and post it somewhere for people to download.
